version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - '27018:27017'

  redis:
    image: bitnami/redis:6.0.16
    container_name: redis_server
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes