export enum TokenReason {
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
    RESET_PASSWORD = 'RESET_PASSWORD',
    VERIFICATION = 'VERIFICATION',
    CHANGE_PASSWORD = 'CHANGE_PASSWORD',
}

export enum TokenStatus {
    EXPIRED = 'EXPIRED',
    ALIVE = 'ALIVE',
}